### ISSUE TITLE
Cannot add new User Note

### ISSUE THREAD

**Issue by alexandraciobica** [joomla-projects/gsoc18_enhance_users#13] opened 2018-06-25 08:57 UTC
### Steps to reproduce the issue
1. Login to backend
2. Go to User Notes > New
3. Fill in the required data > Save

### Expected result
New user note is created.

### Actual result
An error occurs when trying to save.
<img width="318" alt="screen shot 2018-06-22 at 12 21 20" src="https://user-images.githubusercontent.com/18381652/41839728-a98845be-786c-11e8-88e3-aef3153bd703.png">

### Additional comments

The check method from NotesTable misses the return statement.
https://github.com/alexandraciobica/joomla-cms/blob/54b28ba7f844bcd72fe4b55d36c633fb92491d2f/administrator/components/com_users/Table/NoteTable.php#L174
If this is fixed, the following error occurs when trying to save:
<img width="598" alt="screen shot 2018-06-22 at 12 25 46" src="https://user-images.githubusercontent.com/18381652/41839987-4de6d1b6-786d-11e8-9e75-8ed6ece82827.png">

**Comment by wilsonge** [comment] 2018-06-25 09:21
See https://github.com/joomla/joomla-cms/pull/20831

**Comment by alexandraciobica** [comment] 2018-06-25 09:48
I know about that, I forgot to link it in my issue. I added this issue here because I talked with Andrei and   we think that the modified_user_id should be default 0 in the db. And I talked with my mentors to add the issue and talk about this.

**Comment by alexandraciobica** [comment] 2018-06-25 10:34
So, should I change the db schema, or is it ok like Andrei did it, by setting the modified_user_id = 0 in the NotesTable?

**Comment by laoneo** [comment] 2018-06-25 14:13
We should wait till the issue is fixed in upstream and then we merge it back here. No need to do it twice.

**Comment by wilsonge** [comment] 2018-06-25 14:18
Setting a default in the DB is actually a better fix. Like how com_content works https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L330

**Comment by alexandraciobica** [comment] 2018-06-25 14:40
Yes, that's what I was thinking about too. How do we proceed? I can do it, but I can't push on Andrei's branch.

**Comment by laoneo** [comment] 2018-06-25 14:47
Make a new pr in the main repo.

**Closed as completed** 2018-07-01 17:03 UTC
Labels: bug
